Further improvements to the build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,8 +33,10 @@ usage()
    echo "     --reentrant        Build fully reentrant version of library"
    echo "     --single           Faster non-reentrant version of library (default)"
    echo "     CC=<name>          Use the C compiler with the given name"
+   echo "     CXX=<name>         Use the CXX compiler with the given name"
    echo "     AR=<name>          Use the AR library builder with the given name"
    echo "     CFLAGS=<flags>     Pass the given flags to the compiler"
+   echo "     FLINT_TUNE=<flags> Pass the given additional flags to the compiler"
    echo "     ABI=[32|64]        Tell the compiler to use given ABI"
 }
 
@@ -83,8 +85,14 @@ while [ "$1" != "" ]; do
       CC)
          CC=$VALUE
          ;;
+      CXX)
+         CXX=$VALUE
+         ;;
       CFLAGS)
          CFLAGS=$VALUE
+         ;;
+      FLINT_TUNE)
+         FLINT_TUNE=$VALUE
          ;;
       ABI)
          ABI=$VALUE
@@ -105,13 +113,13 @@ fi
 
 if [ -d "${MPIR_DIR}/lib" ]; then
    MPIR_LIB_DIR="${MPIR_DIR}/lib"
-   MPIR_INCLUDE_DIR="${MPIR_DIR}/include"
+   MPIR_INC_DIR="${MPIR_DIR}/include"
 elif [ -d "${MPIR_DIR}/lib64" ]; then
    MPIR_LIB_DIR="${MPIR_DIR}/lib64"
-   MPIR_INCLUDE_DIR="${MPIR_DIR}/include"
+   MPIR_INC_DIR="${MPIR_DIR}/include"
 elif [ -d "${MPIR_DIR}/.libs" ]; then
    MPIR_LIB_DIR="${MPIR_DIR}/.libs"
-   MPIR_INCLUDE_DIR="${MPIR_DIR}"
+   MPIR_INC_DIR="${MPIR_DIR}"
 else
    echo "Invalid MPIR directory"
    exit 1
@@ -119,49 +127,51 @@ fi
 
 if [ -d "${MPFR_DIR}/lib" ]; then
    MPFR_LIB_DIR="${MPFR_DIR}/lib"
-   MPFR_INCLUDE_DIR="${MPFR_DIR}/include"
+   MPFR_INC_DIR="${MPFR_DIR}/include"
 elif [ -d "${MPFR_DIR}/lib64" ]; then
    MPFR_LIB_DIR="${MPFR_DIR}/lib64"
-   MPFR_INCLUDE_DIR="${MPFR_DIR}/include"
+   MPFR_INC_DIR="${MPFR_DIR}/include"
 elif [ -d "${MPFR_DIR}/.libs" ]; then
    MPFR_LIB_DIR="${MPFR_DIR}/.libs"
-   MPFR_INCLUDE_DIR="${MPFR_DIR}"
+   MPFR_INC_DIR="${MPFR_DIR}"
 elif [ -d "${MPFR_DIR}/src/.libs" ]; then
    MPFR_LIB_DIR="${MPFR_DIR}/src/.libs"
-   MPFR_INCLUDE_DIR="${MPFR_DIR}/src"
+   MPFR_INC_DIR="${MPFR_DIR}/src"
 else
    echo "Invalid MPFR directory"
    exit 1
 fi
 
-if [ -d "${NTL_DIR}/lib" ]; then
-   NTL_LIB_DIR="${NTL_DIR}/lib"
-   NTL_INCLUDE_DIR="${NTL_DIR}/include"
-elif [ -d "${NTL_DIR}/lib64" ]; then
-   NTL_LIB_DIR="${NTL_DIR}/lib64"
-   NTL_INCLUDE_DIR="${NTL_DIR}/include"
-else
-   echo "Invalid NTL directory"
-   exit 1
-fi
-
-if [ -d "${BLAS_DIR}" ]; then
-   BLAS_LIB_DIR="${BLAS_DIR}"
-   BLAS_INCLUDE_DIR="${BLAS_DIR}"
-else
-   echo "Invalid BLAS directory"
-   exit 1
-fi
-
-#configure extra libraries
-
 if [ "$WANT_NTL" = "1" ]; then
-    EXTRA_LIBS="$EXTRA_LIBS -lntl"
+   if [ -d "${NTL_DIR}/lib" ]; then
+      NTL_LIB_DIR="${NTL_DIR}/lib"
+      NTL_INC_DIR="${NTL_DIR}/include"
+   elif [ -d "${NTL_DIR}/lib64" ]; then
+      NTL_LIB_DIR="${NTL_DIR}/lib64"
+      NTL_INC_DIR="${NTL_DIR}/include"
+   else
+      echo "Invalid NTL directory"
+      exit 1
+   fi
+   EXTRA_LIBS_DIRS="${EXTRA_LIBS_DIRS} ${NTL_LIB_DIR}"
+   EXTRA_LIBS="${EXTRA_LIBS} -lntl"
+   EXTRA_INCS_DIRS="${EXTRA_INCS_DIRS} ${NTL_INC_DIR}"
 fi
 
 if [ "$WANT_BLAS" = "1" ]; then
-    EXTRA_LIBS="$EXTRA_LIBS -lopenblas"
+   if [ -d "${BLAS_DIR}" ]; then
+      BLAS_LIB_DIR="${BLAS_DIR}"
+      BLAS_INC_DIR="${BLAS_DIR}"
+   else
+      echo "Invalid BLAS directory"
+      exit 1
+   fi
+   EXTRA_LIBS_DIRS="${EXTRA_LIBS_DIRS} ${BLAS_LIB_DIR}"
+   EXTRA_LIBS="${EXTRA_LIBS} -lopenblas"
+   EXTRA_INCS_DIRS="${EXTRA_INCS_DIRS} ${BLAS_INC_DIR}"
 fi
+
+#configure extra libraries
 
 CONFIG_DEFINES="${CONFIG_DEFINES}\n#define HAVE_BLAS ${WANT_BLAS}"
 
@@ -279,7 +289,7 @@ if [ -z "$FLINT_TUNE" ]; then
    fi
 fi
 
-# defaults for CC and CXX
+# defaults for CC, CXX and AR
 
 if [ -z "$CC" ]; then
    CC=gcc
@@ -287,6 +297,10 @@ fi
 
 if [ -z "$CXX" ]; then
    CXX=g++
+fi
+
+if [ -z "$AR" ]; then
+   AR=ar
 fi
 
 # Test for popcnt flag and set needed CFLAGS
@@ -353,19 +367,19 @@ echo "" >> Makefile
 echo "FLINT_STATIC=$STATIC" >> Makefile
 echo "FLINT_SHARED=$SHARED" >> Makefile
 echo "WANT_NTL=$WANT_NTL" >> Makefile
+echo "WANT_BLAS=$WANT_BLAS" >> Makefile
+echo "EXTRA_LIBS_DIRS=$EXTRA_LIBS_DIRS" >> Makefile
 echo "EXTRA_LIBS=$EXTRA_LIBS" >> Makefile
+echo "EXTRA_INCS_DIRS=$EXTRA_INCS_DIRS" >> Makefile
 echo "FLINT_MPIR_LIB_DIR=$MPIR_LIB_DIR" >> Makefile
-echo "FLINT_MPIR_INCLUDE_DIR=$MPIR_INCLUDE_DIR" >> Makefile
-echo "FLINT_BLAS_LIB_DIR=$BLAS_LIB_DIR" >> Makefile
-echo "FLINT_BLAS_INCLUDE_DIR=$BLAS_INCLUDE_DIR" >> Makefile
+echo "FLINT_MPIR_INC_DIR=$MPIR_INC_DIR" >> Makefile
 echo "FLINT_MPFR_LIB_DIR=$MPFR_LIB_DIR" >> Makefile
-echo "FLINT_MPFR_INCLUDE_DIR=$MPFR_INCLUDE_DIR" >> Makefile
-echo "FLINT_NTL_LIB_DIR=$NTL_LIB_DIR" >> Makefile
-echo "FLINT_NTL_INCLUDE_DIR=$NTL_INCLUDE_DIR" >> Makefile
+echo "FLINT_MPFR_INC_DIR=$MPFR_INC_DIR" >> Makefile
 echo "" >> Makefile
 echo "FLINT_LIB=$FLINT_LIB" >> Makefile
 echo "CC=$CC" >> Makefile
 echo "CXX=$CXX" >> Makefile
+echo "AR=$AR" >> Makefile
 echo "CFLAGS=$CFLAGS" >> Makefile
 echo "PICFLAG=$PICFLAG" >> Makefile
 echo "PREFIX=$PREFIX" >> Makefile
